name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: '@IntegratorPortalCIBot'
          token: ${{ secrets.BotToken }}
          message: |
            🚀 *New Commit Made!*
            _Author_: ${{ github.actor }}
            _Commit Message_: ${{ github.event.commits[0].message }}
            
            _Repository_: ${{ github.repository }}
            
            [See changes here](https://github.com/${{ github.repository }}/commit/${{github.sha}})